<?php

namespace App\Filament\Resources\ProductResource\Pages;

use App\Filament\Resources\ProductResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditProduct extends EditRecord
{
    protected static string $resource = ProductResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if(array_key_exists('category_id',$data)){
            unset($data['category_id']);
        }
        return $data;
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {

        $data['category_id'] = $this->record->subcategory->category->id;
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
